### ISSUE TITLE
could anyone give me some advise?

### ISSUE THREAD

**Issue by aa3396896** [lucasb-eyer/pydensecrf#104]
- #75 
still the problem
however,no one give the way to solve it
i use a new environment with
py 3.5
cython 0.26
pydensecrf 1.0rc3

in the code, it can show the fucnction 
dcrf.DenseCRF def __init__(self,
             *args: Any,
             **kwargs: Any) -> None
The most base type
Documentation is copied from:
object
  < Python 3.5 (py35) >

but turn to run it will be
AttributeError: module 'pydensecrf.densecrf' has no attribute 'DenseCRF'

feelsbadman

**Comment by aa3396896** [comment]
ok,i think i solve it,so silly noob as i

**Comment by ShihuaiXu** [comment]
哥 请问您是怎么解决的 我也遇到了一样的问题

**Comment by huixiancheng** [comment]
我当时的错误好像是import路径有问题，我把下载下的包中的pydensecrf文件删掉就行了，希望有参考。

**Comment by ShihuaiXu** [comment]
> 我当时的错误好像是import路径有问题，我把下载下的包中的pydensecrf文件删掉就行了，希望有参考。

谢谢
