### ISSUE TITLE
Package import problem

### ISSUE THREAD

**Issue by pkorus** [lucasb-eyer/pydensecrf#11]
I've successfully installed the library using:

```bash
pip install git+https://github.com/lucasb-eyer/pydensecrf.git
```

Now I've got 4 files in `/usr/lib64/python2.7/site-packages/pydensecrf`:
```
densecrf.so  eigen.so  utils.py  utils.pyc
```

However, I cannot import the library in Python. Both:

```python
import pydensecrf.densecrf
import densecrf
```

are unsuccessful (`/usr/lib64/python2.7/site-packages/` is in `sys.path`). If I explicitly append `/usr/lib64/python2.7/site-packages/pydensecrf` to `sys.path`, then Python can locate the densecrf library (`import densecrf`), but I get an import error:

`ImportError: No module named pydensecrf.eigen`

The problem has been observed under CentOS 7 and Debian Jessie.

**Comment by lucasb-eyer** [comment]
At first sight it seems like we're not installing the `__init__.py` file, which is a bug. I'll try to fix it over the weekend, but if anyone (@rodrigob maybe?) has an idea before that, I'd be grateful.

**Comment by rshanor** [comment]
I am currently having the same issue, after adding pydensecrf to the syspath I get a pydensecrf.eigen error as well.

**Comment by rshanor** [comment]
@pkorus did you ever find a workaround?

**Comment by pkorus** [comment]
In fact your first suggestion (adding `__init__.py`) did the trick for me.

**Comment by rshanor** [comment]
Just move that file into the folder? Thanks!

**Comment by pkorus** [comment]
Just to be clear - after installing the package through pip:
```
>> touch /usr/lib64/python2.7/site-packages/pydensecrf/__init__.py
```
And then you can import the package as `import pydensecrf.densecrf`

**Comment by pkorus** [comment]
Just to be clear - after installing the package through pip:
```
>> touch /usr/lib64/python2.7/site-packages/pydensecrf/__init__.py
```
And then you can import the package as `import pydensecrf.densecrf`

**Comment by lucasb-eyer** [comment]
Yeah exactly. The problem is that `setup.py` doesn't put it there, and I didn't get around to fixing that yet. PRs are welcome, otherwise I'll give it a go sometime in the next couple weeks.

**Comment by rshanor** [comment]
Awesome! Works for me too. Thanks guys.

**Comment by JohanCao** [comment]
Hi Guys,

After I successfully installed pydensecrf on Ubuntu 14.04, I could not find file "__init__.py". The folder /usr/lib/python2.7/site-packages/ is empty. Could someone help me? Many thanks!

**Comment by lucasb-eyer** [comment]
I think I fixed it, but it would be nice to have confirmation from someone. You can do `pip uninstall pydensecrf` and then install it again with pip as stated in the README.
