### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by sqy12** [lucasb-eyer/pydensecrf#15]
In your example, the labels after relabelling is ranged from 0 - 2 and the M is equal to 3. But the map computed is ranged from 1 - 2 which means there is a class gone?
The result of the computation is quite wield in my case.

**Comment by sqy12** [comment]
But it's not a large problem. How I can change the weight of each potential?

**Comment by lucasb-eyer** [comment]
These are again two different questions, please try to ask only one question per issue and prefer opening multiple issues for multiple questions.

I've clarified the answer to your first question in the first commit (1043a71) and to your second question in the second commit (3846e8a)
