### ISSUE TITLE
Modify Q between inference steps

### ISSUE THREAD

**Issue by pierrebaque** [lucasb-eyer/pydensecrf#16]
Hello,

I am using your code and for some reason, I would need to modify Q between the steps. 
It means that I want to modify the initial point of each inference step (not let it be the output of the previous step by default). Is it something that can easily be handled with your implementation?

Let's say, for instance that I want to do something like:

for s in steps:
        d.stepInference(Q, tmp1, tmp2)
        Q = 0.5*Q + 0.5*my_Q

Of course, this doesn't work and I get the following error:

"Argument 'Q' has incorrect type (expected pydensecrf.eigen.MatrixXf, got numpy.ndarray)"

Cheers.

Pierre

**Comment by lucasb-eyer** [comment]
Yes, the way you describe is almost correct. As the error is hinting, you need to convert `Q` to a wrapped Eigen `MatrixXf` before passing it to `stepInference`. I have written the `eigen.matrixXf` function for this, you can see an [example usage here in the eigen unit-test](https://github.com/lucasb-eyer/pydensecrf/blob/1463feb/pydensecrf/test_eigen.py#L10).

I'm closing this issue, but feel free to reopen if that doesn't work. If it works, I would be happy to hear of your use-case and/or paper once it's out!
