### ISSUE TITLE
confidence score

### ISSUE THREAD

**Issue by zhengshou** [lucasb-eyer/pydensecrf#23]
Hi,

I am not familiar with denseCRF but I am wondering would it be possible (or make sense) to obtain confidence score for prediction at each pixel from Q ? Thanks.

Best,
Zheng

**Comment by lucasb-eyer** [comment]
So why don't you read the original paper that I'm also referencing in the README? The paper explains exactly what Q is and should answer your question. Q is an approximative distribution, so you could use it as-is, but it's not clear how well-behaved it will be. I recommend running some tests and seeing how Q behaves in your case.

Closing as it's not an actual issue.

**Comment by zhengshou** [comment]
Thank you and sorry for confusion. I guess my problem actually is not sure how to read values out of Q which is pydensecrf.eigen.MatrixXf object. But now I find can simply convert it as numpy array.

**Comment by lucasb-eyer** [comment]
Ah, I didn't read it like that, sorry. Yes, it implements the buffer interface so `np.array(Q)` should just work.
