### ISSUE TITLE
Add examples similar to the ones in the original C++ code

### ISSUE THREAD

**Issue by kevin-keraudren** [lucasb-eyer/pydensecrf#3]
For instance:
https://gist.github.com/kevin-keraudren/a8accc61bd5ee0ebb420

Which gives with `anno1.ppm` and `im1.ppm` from the C++ example folder:
![image](https://cloud.githubusercontent.com/assets/802153/12142634/8665c71c-b471-11e5-9f22-7c042c860adf.png)

![image](https://cloud.githubusercontent.com/assets/802153/12142642/9359298c-b471-11e5-887a-f85e10c27557.png)

![image](https://cloud.githubusercontent.com/assets/802153/12142570/089df8b8-b471-11e5-8311-401d1c27863d.png)

**Comment by lucasb-eyer** [comment]
Nice, thank you!

Would you mind either opening a PR which adds this file, or explicitly allowing me to add your file to the repo under MIT license?

**Comment by kevin-keraudren** [comment]
Hi, I noticed at the end of the week that the example was not quite right, hence I made another pull request to fix it: https://github.com/lucasb-eyer/pydensecrf/pull/5

With this fix and the default settings, the output for the image above becomes:

![image](https://cloud.githubusercontent.com/assets/802153/12224243/ad6a416a-b7e3-11e5-9392-07947a6c64fa.png)

Explanations and a better highlight of the impact of the fix is presented in the new PR.

**Comment by lucasb-eyer** [comment]
Fixed by #4
