### ISSUE TITLE
Bad shape for unary energy

### ISSUE THREAD

**Issue by MehulAjax21** [lucasb-eyer/pydensecrf#34]
Hi Lukas,

I see the above error while running the densecrf. i will list down the steps here:

d = dcrf.DenseCRF2D(224, 224, 8)
U = unary_from_softmax(unary)  # Unary is output of softmax
d.setUnaryEnergy(U)

Here is get the above error: Bad shape for unary energy (Need (224, 224), got (8, 50176))

I think a similar bug is fixed in a commit (b5e13a9). could you please update the same for the setUnaryEnergy method also?

**Comment by lucasb-eyer** [comment]
Thanks for the report, looks like the checks I added today aren't the best :smile: It's late here, so I'll see what's up tomorrow!

**Comment by lucasb-eyer** [comment]
Ok this was an actual bug that I fixed in the above commit, please try it out!

**Comment by MehulAjax21** [comment]
Hi Lukas thanks for your reply.
I had to work last night So I also fixed the bug myself. I did the same changes. Also, as I have tested it, the changes are fine.

**Comment by bionick87** [comment]
Hey lucas,

I had the same bugs:

  File "pydensecrf/densecrf.pyx", line 82, in pydensecrf.densecrf.DenseCRF.setUnaryEnergy
ValueError: Bad shape for unary energy (Need (1, 268800), got (2, 16129))****
