### ISSUE TITLE
how can i install this with visual studio 2013?

### ISSUE THREAD

**Issue by xiaoshumei** [lucasb-eyer/pydensecrf#36]
when i pip3 install, i got an error :visual c++ 14.0 is required!

**Comment by lucasb-eyer** [comment]
I guess that means Cython needs vs2015 :smile: I have no idea if there's a way to make it work with vs2013, so if anyone has a PR for that, I'd merge it, but I won't spend time trying to find that out myself, sorry!

**Comment by lucasb-eyer** [comment]
Going to close this as it's about a 5 year-old version. If anyone has a PR for this, it's still welcome.
