### ISSUE TITLE
Labels looked weird after densecrf

### ISSUE THREAD

**Issue by raymondchua** [lucasb-eyer/pydensecrf#38]
Hi,
Before I apply dense crf, my labels were looking fine. 
http://imgur.com/fZtEboL
However, after pydensecrf, I have this weird pixels across my image. 
http://imgur.com/54vUQfa
Has anyone faced the same issue?

**Comment by lucasb-eyer** [comment]
You closed the issue, so I assume you fixed it? In that case, could you write down what the problem was so others who might have the same error can know? I'm guessing w/h mixup.

**Comment by raymondchua** [comment]
Hi Lucas, sure. It was because I have NaN and inf values in my probabilities due to the division by zero. Easy fix is to add 1e-3.

**Comment by lucasb-eyer** [comment]
Thank you for having clarified, it might help others in the future!
