### ISSUE TITLE
How to specify my customized pairwise term?

### ISSUE THREAD

**Issue by zeakey** [lucasb-eyer/pydensecrf#40]
Hi all,
I've designed my own pixel to pixel similarity metric and I want to make it part of the pairwise term. How can I implement this?

Can someone give me some tips?

**Comment by lucasb-eyer** [comment]
You can add any arbitrary pairwise energy to the DenseCRF through the `void addPairwiseEnergy(const c_MatrixXf &features, LabelCompatibility*, KernelType, NormalizationType)` method, have a look at [`create_pairwise_gaussian(sdims, shape)`](https://github.com/lucasb-eyer/pydensecrf/blob/master/pydensecrf/utils.py#L89) and [`create_pairwise_bilateral(sdims, schan, img, chdim=-1)`](https://github.com/lucasb-eyer/pydensecrf/blob/master/pydensecrf/utils.py#L114) in `utils.py` for two examples of methods creating a pairwise term.

Please let me know if that works, and consider contributing an example if it does!

**Comment by lucasb-eyer** [comment]
Closing due to no further question/feedback.
