### ISSUE TITLE
Why is this package not on PyPI?

### ISSUE THREAD

**Issue by MiguelMonteiro** [lucasb-eyer/pydensecrf#41]
Why is this package not on PyPI, is there a particular reason? It would be extremely useful if it was, I know it is unrelated but I am having a lot of trouble getting to work as dependency for my own package  because of it.

**Comment by lucasb-eyer** [comment]
Hi. There is no real reason besides that I'm lazy :)

I didn't expect this project to become popular, so didn't bother. Thank you for the reminder, I will look into it "sometime soon".

**Comment by lucasb-eyer** [comment]
Actually, I just did it. There's a [release-candidate on PyPI](https://pypi.python.org/pypi/pydensecrf) now. I did some quick testing, but please give it a try and let me know if it works for you; this is my first package on PyPI.

**Comment by lucasb-eyer** [comment]
Closing the issue. Please open new issues if the PyPI package doesn't work.

**Comment by MiguelMonteiro** [comment]
Sorry, have been on vacation, just tested it, it seems to be working fine.

**Comment by lucasb-eyer** [comment]
Cool, no worries and thanks for the feedback!
