### ISSUE TITLE
Import error for densecrf.so: "undefined symbol"

### ISSUE THREAD

**Issue by Ryan-Lima** [lucasb-eyer/pydensecrf#42]
Using python 2.7.13 Anaconda 4.4.0 (64 bit) on Ubuntu 16.04
Installed pydensecrf from git as per instructions: no installation errors. However, when I issue

```
import pydensecrf.densecrf as dcrf
```

I get the following error

```
ImportError: /home/ryanelima/anaconda2/lib/python2.7/site-packages/pydensecrf/densecrf.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E
```

I have tried uninstalling and reinstalling system cython and pip cython (both as user and root), but problem persists. Also tried

```
nm -C  /home/ryanelima/anaconda2/lib/python2.7/site-packages/pydensecrf/densecrf.so
```

Please advise

Thanks

**Comment by lucasb-eyer** [comment]
Please read the readme :smile:  This exact problem is described [in the README](https://github.com/lucasb-eyer/pydensecrf#undefined-symbol-when-importing).

Feel free to re-open the issue with more info if that doesn't help.
