### ISSUE TITLE
Fail to build library in virtualenv due to redeclaration of round() function

### ISSUE THREAD

**Issue by trangnambeo** [lucasb-eyer/pydensecrf#44]
Hi Luca,
I tried to build/install library inside a virtual environment created by Anaconda3 but it failed, the error is:

pydensecrf/densecrf/src/permutohedral.cpp:31:26: error: ambiguating new declaration of 'int round(double)'
 inline int round(double X) {
                          ^
Looks like there is another round() function inside <cmath> , I commented  the following lines in permutohedral.cpp so It could build just fine.

//#ifdef WIN32
//inline int round(double X) {
//      return int(X+.5);
//}
//#endif

Is it correct to do so? 
Thanks,

**Comment by lucasb-eyer** [comment]
Hmm, so this is on windows, right? I have not built this on windows in a long long time. Actually, it seems like the `round` function is not used at all in the file, [the only reference to it is commented-out](https://github.com/lucasb-eyer/pydensecrf/blob/d824b89ee3867bca3e90b9f04c448f1b41821524/pydensecrf/densecrf/src/permutohedral.cpp#L377).

If this works for you, could you please make a pull-request with that change?
