### ISSUE TITLE
question about addPairwiseGaussian and addPairwiseBilateral

### ISSUE THREAD

**Issue by qdinfish** [lucasb-eyer/pydensecrf#45]
Hi,

I didn't understand what are the means of sxy=3 , sxy=80 and srgb=13?

Could you help it ?

Thanks 

d.addPairwiseGaussian(sxy=3, compat=3)
d.addPairwiseBilateral(sxy=80, srgb=13, rgbim=im, compat=10)

**Comment by howardgriffin** [comment]
I have the same question .Do you understand now?

**Comment by Toz3wm** [comment]
From the original paper "Efficient Inference in Fully Connected CRFs with Gaussian Edge Potentials", this formula : 
![capture du 2018-02-13 13-50-37](https://user-images.githubusercontent.com/10962198/36150757-01122bf2-10c5-11e8-97d2-2e833c1c9461.png)

I think sxy in addPairWiseGaussian is theta_c, and sxy and srgb are respectively theta_a and theta_b. I might be wrong, however if this is not the case, then I don't see a  hyper parameter that could fit to this sxy.

**Comment by dingfg** [comment]
sxy(PosXStd and PosYStd)
sxy(Bi_X_Std and Bi_Y_Std), srgb(Bi_R_Std , Bi_G_Std and Bi_B_Std)

**Comment by lucasb-eyer** [comment]
@Toz3wm is correct (again :smile:) and @dingfg is correct too. I have added a note to the README.

**Comment by IssamLaradji** [comment]
what does `compat` refer to in the formula ? is it `w` ?

**Comment by lucasb-eyer** [comment]
@IssamLaradji from the readme:

> These are label-compatibilites `µ(xi, xj)`

which is what they are called in the paper too. They are not visible in the formula screen-shotted by @Toz3wm.
