### ISSUE TITLE
Unary potential

### ISSUE THREAD

**Issue by XhqGlorry11** [lucasb-eyer/pydensecrf#51]
@lucasb-eyer Hi lucas, can you tell me how does unary potential calculated in your code? It seems that you just use the "class probabilities per pixel" to calculate unary potential. While the paper use information of the original image, e.g. color, location... Can you give me tips? Thanks!
![image](https://user-images.githubusercontent.com/22702027/33586322-d790860a-d9a3-11e7-865c-8901803ec73e.png)

**Comment by lucasb-eyer** [comment]
Hi @XhqGlorry11 sorry for the late answer. It is your task to come up with a unary potential which makes sense for your application. It is not part of PyDenseCRF to compute one, but rather you compute one and give it to PyDenseCRF. In the past, it was typically RandomForest output, and nowadays, many people use the SoftMax output of a CNN as unary potentials.

Closing the issue as it's not actually an issue.
