### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'float' but got 'double'

### ISSUE THREAD

**Issue by rw1993** [lucasb-eyer/pydensecrf#52]
Try below code and get ValueError.
>>> import numpy as np
>>> import pydensecrf.densecrf as dcrf
>>> d = dcrf.DenseCRF(80, 2)
>>> U = np.random.random(size=(2, 80))
>>> d.setUnaryEnergy(U)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    d.setUnaryEnergy(U)
  File "pydensecrf/densecrf.pyx", line 80, in pydensecrf.densecrf.DenseCRF.setUn
aryEnergy (pydensecrf/densecrf.cpp:3370)
ValueError: Buffer dtype mismatch, expected 'float' but got 'double'

**Comment by Nandayang** [comment]
@rw1993 Hi, i m facing the same problem. Do you solve this ?

**Comment by lucasb-eyer** [comment]
People had this error before (#49) and it's a user error. I think the error is pretty clear: you should pass a float, but you're passing a double. Fix by doing `U = U.astype(np.float32)`. I'll add a note to the FAQ in the README.
