### ISSUE TITLE
The example to use the package

### ISSUE THREAD

**Issue by howardgriffin** [lucasb-eyer/pydensecrf#53]
Could someone show me how to use pydensecrf package or the examples about it? Thank you in advance!

**Comment by howardgriffin** [comment]
And how to run utils_example.py in examples ? What should sys.argv be?

**Comment by lucasb-eyer** [comment]
Hi, just follow the instructions in the README. Installation and usage are both described there.

If there is an actual problem following those steps, please open an issue with what you have done, and what error you encounter.
