### ISSUE TITLE
How to get the hyperparameters?

### ISSUE THREAD

**Issue by lixiang-ucas** [lucasb-eyer/pydensecrf#54]
Thanks for you wonderful work. I have trying inferring using your code, but it works  not good. I'm wondering how to find the best hyperparameters? Have you implemented the learning procedure?

**Comment by lucasb-eyer** [comment]
I have not implemented the learning procedure, but am happy to accept PRs implementing it, [as mentioned in the README](https://github.com/lucasb-eyer/pydensecrf#learning).

Besides that, finding hyperparameters is an open question in ML, so nothing I can help with in a github issue :smile: Use a validation-set and do search.
