### ISSUE TITLE
Problem installation windows

### ISSUE THREAD

**Issue by arnaudDup** [lucasb-eyer/pydensecrf#62]
Hi, recently i tried to reinstall the librairy on a Windows computer and got the following error:

"  LINK : error LNK2001: unresolved external symbol PyInit_pydensecrf/eigen
    build\temp.win-amd64-3.6\Release\pydensecrf\eigen.cp36-win_amd64.lib : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120" 

But the installation works well on a linux computer with the same version of pip and python:
pip version =  9.0.1
python version = 3.6.3

Do you have any idea on where the problem could be?

**Comment by lucasb-eyer** [comment]
Hi,

I'm afraid I can't help here, as I don't have a windows dev machine anymore. There are a few windows-related issues: #61, #47, #36, so there seems to be some problem. I'm happy to accepte PRs fixing this, but can't look into it myself, unfortunately.

**Comment by lucasb-eyer** [comment]
(Maybe the Cython version is relevant here too, did you try updating to the newest Cython?)

**Comment by aaronjie** [comment]
I find this problem was solved after Cython installed ;)

**Comment by lucasb-eyer** [comment]
Thank you for getting back to this, I have added a note to the README.
