### ISSUE TITLE
ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by mokii** [lucasb-eyer/pydensecrf#66]
error: File "stringsource", line 345, in View.MemoryView.memoryview.__cinit__ (pydensecrf/densecrf.cpp:7881)
ValueError: ndarray is not C-contiguous
I use the 2D softmax_to_unary, but get the above error, what is the problem?

**Comment by reynoldscem** [comment]
Use `numpy.ascontiguousarray`

**Comment by lucasb-eyer** [comment]
Thanks @reynoldscem, that is correct.
