### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by atemysemicolon** [lucasb-eyer/pydensecrf#7]
If I were to introduce a pure pythonic way of training with some kind of grid-search, instead of interfacing with the C code, do you think it would make sense?

To get : sx, sy, sr, sg, sb for the gaussian and bilateral functions

I'd put in a bunch of parameters, and see for which the error over my dataset is the least, and use those at test time. Does it make sense, or do I have to do more?

**Comment by lucasb-eyer** [comment]
I think that would be an OK thing to do in general, but I don't think this has a place in the wrapper: it belongs in your code. So I'm closing this.

If you need the wrapper to expose some additional functionality from the C library for this, feel free to re-open the issue and explain in more detail.
