### ISSUE TITLE
module ‘pydenecrf.densecrf’ has no attribute 'DenseCRF2D'

### ISSUE THREAD

**Issue by liangfengjiao** [lucasb-eyer/pydensecrf#71]
densecrf file was coded by C++, why can not call 'DenseCRF2D'

**Comment by lucasb-eyer** [comment]
Hi, it is likely you did not properly install the package. There is no way for me to help you given that you do not give any information.

I'm closing the issue, but feel free to re-open it **with exact steps required to reproduce the problem**.

**Comment by liangfengjiao** [comment]
Thanks very much，I have solved this problem.

在2018-07-15 18:50:37，梁凤娇16120383@bjtu.edu.cn写道：

Closed #71.

**Comment by lucasb-eyer** [comment]
Could you please tell me what step solved it for you?

**Comment by manishh** [comment]
I am also facing this when I am simply trying to run this simple 3-line sample code - 

```
import numpy as np
import pydensecrf.densecrf as dcrf

d = dcrf.DenseCRF2D(640, 480, 5)  # width, height, nlabels

```
Any pointers how to get this running? README instructions are not helpful.

**Comment by Romulan12** [comment]
After installing with: !pip install pydensecrf
Try:
import pydensecrf.densecrf 
from pydensecrf.densecrf import DenseCRF2D
