### ISSUE TITLE
Bad shape for unary energy 

### ISSUE THREAD

**Issue by bionick87** [lucasb-eyer/pydensecrf#73]
Hi, 

I had the following bug:

  File "pydensecrf/densecrf.pyx", line 82, in pydensecrf.densecrf.DenseCRF.setUnaryEnergy
ValueError: Bad shape for unary energy Need (1, 268800), got (2, 268800))

Size of input image is 420x640, whit 2 lables

I have installed the version of the github repository.

Thanks.

**Comment by bionick87** [comment]
solved!

**Comment by Deeperss** [comment]
> solved!

How can you solved the problem? I get the same issue. Can you tell me ,Thanks.

**Comment by smaamehm** [comment]
please share the solution

**Comment by Junaid199f** [comment]
Could you please share the solution as i also got this error
