### ISSUE TITLE
Processing one channel image, but the output always black

### ISSUE THREAD

**Issue by AneonCode** [lucasb-eyer/pydensecrf#77]
Hi,
  I'm using pydensecrf to process my one channel image, but I can only get the result array full of zero. Can you help me to solve it?
  My code is on the github: https://github.com/AneonCode/CRFTest

**Comment by AneonCode** [comment]
solved

**Comment by lucasb-eyer** [comment]
Hi there,

I'm glad you solved it, but it is always nice to write down how you solved it/what was your mistake. That's because in the future people with the same mistake might find your post and it would help them :)
