### ISSUE TITLE
Installing on win10 64bit python3.7

### ISSUE THREAD

**Issue by ezrabest** [lucasb-eyer/pydensecrf#89]
I have tried all solutions suggested in other issues, but the installation failed,  with pip and with .git commands. I'm running on win10 64bit python 3.7 all installation tools were updated. 
the error message:
`(base) C:\Users\Ezra>pip install git+https://github.com/lucasb-eyer/pydensecrf.git
Collecting git+https://github.com/lucasb-eyer/pydensecrf.git
  Cloning https://github.com/lucasb-eyer/pydensecrf.git to c:\users\ezra\appdata\local\temp\pip-req-build-2k6r0wk2
  Running command git clone -q https://github.com/lucasb-eyer/pydensecrf.git 'C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2'
Building wheels for collected packages: pydensecrf
  Building wheel for pydensecrf (setup.py) ... error
  ERROR: Complete output from command 'c:\users\ezra\appdata\local\continuum\anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Ezra\\AppData\\Local\\Temp\\pip-req-build-2k6r0wk2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Ezra\AppData\Local\Temp\pip-wheel-6plwp_tx' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pydensecrf
  copying pydensecrf\utils.py -> build\lib.win-amd64-3.7\pydensecrf
  copying pydensecrf\__init__.py -> build\lib.win-amd64-3.7\pydensecrf
  running build_ext
  building 'pydensecrf.eigen' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\pydensecrf
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipydensecrf/densecrf/include -Ipydensecrf -Ic:\users\ezra\appdata\local\continuum\anaconda3\include -Ic:\users\ezra\appdata\local\continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tppydensecrf/eigen.cpp /Fobuild\temp.win-amd64-3.7\Release\pydensecrf/eigen.obj
  eigen.cpp
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(120): error C2373: 'Eigen::DenseBase<Derived>::segment': redefinition; different type modifiers
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/DenseBase.h(291): note: see declaration of 'Eigen::DenseBase<Derived>::segment'
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(121): error C2447: '{': missing function header (old-style formal list?)
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(152): error C2373: 'Eigen::DenseBase<Derived>::head': redefinition; different type modifiers
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/DenseBase.h(294): note: see declaration of 'Eigen::DenseBase<Derived>::head'
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(153): error C2447: '{': missing function header (old-style formal list?)
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(184): error C2373: 'Eigen::DenseBase<Derived>::tail': redefinition; different type modifiers
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/DenseBase.h(297): note: see declaration of 'Eigen::DenseBase<Derived>::tail'
  C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(185): error C2447: '{': missing function header (old-style formal list?)
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pydensecrf
  Running setup.py clean for pydensecrf
Failed to build pydensecrf
Installing collected packages: pydensecrf
  Running setup.py install for pydensecrf ... error
    ERROR: Complete output from command 'c:\users\ezra\appdata\local\continuum\anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Ezra\\AppData\\Local\\Temp\\pip-req-build-2k6r0wk2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ezra\AppData\Local\Temp\pip-record-j4m6iof8\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pydensecrf
    copying pydensecrf\utils.py -> build\lib.win-amd64-3.7\pydensecrf
    copying pydensecrf\__init__.py -> build\lib.win-amd64-3.7\pydensecrf
    running build_ext
    building 'pydensecrf.eigen' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\pydensecrf
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ipydensecrf/densecrf/include -Ipydensecrf -Ic:\users\ezra\appdata\local\continuum\anaconda3\include -Ic:\users\ezra\appdata\local\continuum\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tppydensecrf/eigen.cpp /Fobuild\temp.win-amd64-3.7\Release\pydensecrf/eigen.obj
    eigen.cpp
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(120): error C2373: 'Eigen::DenseBase<Derived>::segment': redefinition; different type modifiers
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/DenseBase.h(291): note: see declaration of 'Eigen::DenseBase<Derived>::segment'
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(121): error C2447: '{': missing function header (old-style formal list?)
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(152): error C2373: 'Eigen::DenseBase<Derived>::head': redefinition; different type modifiers
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/DenseBase.h(294): note: see declaration of 'Eigen::DenseBase<Derived>::head'
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(153): error C2447: '{': missing function header (old-style formal list?)
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(184): error C2373: 'Eigen::DenseBase<Derived>::tail': redefinition; different type modifiers
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/DenseBase.h(297): note: see declaration of 'Eigen::DenseBase<Derived>::tail'
    C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\pydensecrf\densecrf\include\Eigen\src/Core/VectorBlock.h(185): error C2447: '{': missing function header (old-style formal list?)
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'c:\users\ezra\appdata\local\continuum\anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Ezra\\AppData\\Local\\Temp\\pip-req-build-2k6r0wk2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Ezra\AppData\Local\Temp\pip-record-j4m6iof8\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Ezra\AppData\Local\Temp\pip-req-build-2k6r0wk2\`

thanks for your assist

**Comment by kimisecond** [comment]
[https://www.lfd.uci.edu/~gohlke/pythonlibs/#pydensecrf](url)
Using a whl prebuilt by LFD, UCI seemed to solve this issue.

However, installation in linux (e.g Ubuntu) still encounters a similar problem (using gcc).

**Comment by captaindavepdx** [comment]
In addition to @kimisecond's solution, to install "whl" file:

pip install pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl

*Change the file name to whichever one you need.

**Comment by tamireiny** [comment]
@thealtruist Can you please give a direct link to pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl? I could not find it

**Comment by thealtruist** [comment]
@tamireiny The link is provided in @kimisecond 's answer. You'll need to copy and paste it into the web browser. And make sure to download the version that matches your Python version and Windows system type. For example, `pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl` refers to Python3.7 and Windows 64-bit.

**Comment by tamireiny** [comment]
@thealtruist I have managed to download the file now, but when I run: 
pip install pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl, I get: 
ERROR: pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.
I have python 3.7, windows 10 64 bit. Any idea how to solve?

**Comment by thealtruist** [comment]
@tamireiny  Can you verify the Python version? `python --version`

**Comment by tamireiny** [comment]
@thealtruist I run python --version
Python 3.7.6

**Comment by thealtruist** [comment]
@tamireiny Can you also verify the system type? 

1. Press “⊞ Windows”
2. Enter "About"
3. Click "About Your PC"
4. Find "System Type"

**Comment by tamireiny** [comment]
@thealtruist 
![image](https://user-images.githubusercontent.com/37779442/93670977-de0b8200-faa7-11ea-85ca-6a712f21cdb5.png)

**Comment by thealtruist** [comment]
@tamireiny Could you also check your pip version? `pip --version`

**Comment by tamireiny** [comment]
@thealtruist , sure: 
pip --version
pip 20.0.2 from c:\users\tamir\appdata\local\programs\python\python36\lib\site-packages\pip (python 3.6)

**Comment by thealtruist** [comment]
@tamireiny It looks like your pip is connected to Python 3.6 and your interpreter is connected to Python 3.7

**Comment by tamireiny** [comment]
@thealtruist You are right, thanks. I used now the pip the is related to python 3.7
Then I try: import pydensecrf.densecrf as dcrf
I get: 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\ShadowRemoval\Source\BDRAR\misc.py", line 4, in <module>
    import pydensecrf.densecrf as dcrf
ImportError: DLL load failed: The specified module could not be found.

What do you suggest?

**Comment by thealtruist** [comment]
@tamireiny Were you able to successfully install pydensecrf using the pip that's related to Python 3.7?

**Comment by tamireiny** [comment]
@thealtruist Yes, when I try to install again I get:
pip install pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Requirement already satisfied: pydensecrf==1.0rc2 from file:///C:/Users/Tamir/anaconda3/Scripts/pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl in c:\users\tamir\anaconda3\lib\site-packages (1.0rc2)

**Comment by thealtruist** [comment]
@tamireiny Previously, have you set the Anaconda path in your Windows PATH Environment Variables?

**Comment by tamireiny** [comment]
@thealtruist Yes
![image](https://user-images.githubusercontent.com/37779442/93671651-6d676400-faad-11ea-8175-3192b26945cf.png)

**Comment by thealtruist** [comment]
@tamireiny I don't use Anaconda but it seems strange that the error is trying to locate modules in Anaconda when you installed pydensecrf using pip.

**Comment by tamireiny** [comment]
@thealtruist I didn't understand your last comment, the error is:
import pydensecrf.densecrf as dcrf
ImportError: DLL load failed: The specified module could not be found.

Why do you think it's trying to locate modules using Anaocnda?

**Comment by thealtruist** [comment]
@tamireiny That was a mistake. I was referring to it referencing the location of the site package.

Requirement already satisfied: pydensecrf==1.0rc2 from file:///C:/Users/Tamir/anaconda3/Scripts/pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl in c:\users\tamir\anaconda3\lib\site-packages (1.0rc2)

**Comment by thealtruist** [comment]
@tamireiny But apparently that's a normal thing so I'm not sure what's causing the error.

**Comment by tamireiny** [comment]
@thealtruist Here in this folder path: C:\Users\Tamir\anaconda3\Scripts>
1. activate
2. conda install -c conda-forge pydensecrf
The result is: 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining python=3.7:  67%|████████████████████████████████████████████████████████████                              | 2/3 [00:00<00:00, 60.73it/s]/failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pydensecrf -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==10.1=0
  - feature:|@/win-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1

Seems that I got reject since there is no support for python 3.7

**Comment by tamireiny** [comment]
@thealtruist This worked for me:
pip install pydensecrf-1.0rc2-cp37-cp37m-win_amd64.whl --no-deps

**Comment by thealtruist** [comment]
@tamireiny Nice, glad you figured it out!

**Comment by mu745511** [comment]
@david-littlefield  AttributeError: module 'pydensecrf.densecrf' has no attribute 'DenseCRF2D' i get this attribute error

**Comment by david-littlefield** [comment]
@mu745511 What are the steps that you used to install?

**Comment by mu745511** [comment]
> @mu745511 What are the steps that you used to install?

import sys 
sys.path.append('github master pydensecrf')

**Comment by david-littlefield** [comment]
@mu745511 It's been a while but I don't think you can just use pip install on this one. I think you need to install the wheel file for your specific Python version, operating system, and system type. You might try installing the wheel file as suggested [here](https://github.com/lucasb-eyer/pydensecrf/issues/89#issuecomment-506245175) and [here](https://github.com/lucasb-eyer/pydensecrf/issues/89#issuecomment-664027512).

**Comment by ezrabest** [comment]
Thanks to all repliers 
Working with Pycharm instead of Anaconda solve the issue
