### ISSUE TITLE
Turn into "proper" package for utils.

### ISSUE THREAD

**Issue by lucasb-eyer** [lucasb-eyer/pydensecrf#9]
See comments in #6, we'd like to make them easily available.

This issue serves as a reminder to myself, and as an indicator to others that this is indeed intended to happen.

**Comment by rodrigob** [comment]
For info, I already implemented this in a private branch.

**Comment by lucasb-eyer** [comment]
I guess since you're notifying me, that private branch will eventually morph into a public PR?

PS: Hey there, I remember you =)

**Comment by rodrigob** [comment]
Created PR #10.

**Comment by lucasb-eyer** [comment]
Fixed over there.
